# Generated by Django 4.0 on 2022-05-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_issuecategory_options_issuecategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/issues/'),
        ),
    ]
